#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.24
#  in conjunction with Tcl version 8.6
#    Jul 08, 2019 04:34:12 PM IST  platform: Linux

import sys
import length
import tumor
import orbital

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def create_l_window():
    length.create_length(root)
    print("pressed length")


def create_t_window():
    tumor.create_tumor(root)
    print("pressed tumor")

def create_o_window():
    orbital.create_orbital(root)
    print("pressed orbital")


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import gui
    gui.vp_start_gui()




